[package]
name = "libninja"
version = "0.1.9"
edition = "2021"
license = "MIT"
description = "Command line tool for OpenAPI client generation."
publish = false
default-run = "libninja"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
integration = []
actix = ["actix-web"]

[dependencies]
anyhow = { version = "1.0.68", features = ["backtrace"] }
log = "0.4.17"
proc-macro2 = "1.0.50"
quote = "1.0.23"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9.17"
syn = "1.0.107"
tokio = { version = "1.24.2", features = ["full"] }
openapiv3-extended = { version = "2.2.0" }
convert_case = "0.6.0"
prettyplease = "0.1.23"
clap = { version = "4.1.4", features = ["derive"] }
tera = "1.17.1"
include_dir = "0.7.3"
regex = "1.7.1"
indoc = "2.0.1"
cargo_toml = "0.15.2"
toml = "0.7.2"
topo_sort = "0.4.0"
url = "2.3.1"
http = "0.2.8"
tracing-ez = "0.3.0"
strum = "0.24.1"
actix-web = { version = "4.3.0", optional = true }
semver = "1.0.16"
indexmap = "1.9.2"
ln-macro = { path = "../macro" }
ln-core = { path = "../core" }
ln-mir = { path = "../mir" }

[dev-dependencies]
env_logger = "0.10.0"
pretty_assertions = "1.3.0"
tempfile = "3.3.0"
