[workspace]
members = [
    "libninja",
    "macro",
    "core",
    "commercial",
]
exclude = [
]

#[patch.crates-io]
#serde_derive = { git = "https://github.com/kurtbuilds/serde" }
#openapiv3-extended = { path = "../openapiv3" }
