[package]
name = "ln-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
convert_case = "0.6.0"
ln-model = { path = "../model" }
openapiv3-extended = "2.0.2"
serde = { version = "1.0.152", features = ["derive"] }
